### ISSUE TITLE
Add a `conda` install option for `htmltools`

### ISSUE THREAD

**Issue by sugatoray** [rstudio/py-htmltools#41]
A conda installation option could be very helpful. I have already started working on this, to add `htmltools` to conda-forge.

Conda-forge PR: 

- https://github.com/conda-forge/staged-recipes/pull/19842

Once the conda-forge PR is merged, you will be able to install the library with conda as follows:

```sh
conda install -c conda-forge htmltools
```

Also see the following `py-shiny` issue:

- https://github.com/rstudio/py-shiny/issues/280

**Comment by cpsievert** [comment]
Thank you!
