### ISSUE TITLE
Should allow HTML dependencies from remote URLs

### ISSUE THREAD

**Issue by wch** [rstudio/py-htmltools#52]
HTML dependencies currently only can be defined with local URLs; we should add support for remote URLs.

**Comment by schloerke** [comment]
Shiny would need to know of the new type once implemented

**Comment by schloerke** [comment]
Related: https://github.com/rstudio/py-htmltools/blob/39e450e5877daafc3f8407ad5fe2a93e345b9a8e/htmltools/_core.py#L899-L901
